<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'role' => 'admin',
                'specialty' => NULL,
                'name' => 'Admin',
                'gender' => 'm',
                'marital_status' => 'single',
                'date_of_birth' => NULL,
                'tel' => '25219853',
                'Governorate' => 'Jendouba',
                'adresse' => 'Jendouba, جندوبة, Tunisie',
                'bio' => NULL,
                'email' => 'admin@admin.com',
                'email_verified_at' => '2021-05-30 20:54:54',
                'password' => '$2y$10$idmPr5ADvyGmiEKHW.Xnu.LMZsMLUK0KAkoSpvEyp8DYJlkAsmk2e',
                'remember_token' => 'BDmxyOmUU5YQvwpX8DSr1RyIe20Po5OF6RavTjDYbXkev5DF5P4sW3MYizjx',
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'created_at' => '2021-03-21 07:16:51',
                'updated_at' => '2021-06-01 08:39:53',
                'last_seen' => '2021-06-01 08:39:53',
            ),
            1 => 
            array (
                'id' => 2,
                'role' => 'E-health Care',
                'specialty' => 'Nurse',
                'name' => 'anis',
                'gender' => 'm',
                'marital_status' => 'single',
                'date_of_birth' => '1996-05-09',
                'tel' => '25219853',
                'Governorate' => 'Tunis',
                'adresse' => 'Rue el mar, Tunis, تونس, Tunisie',
                'bio' => NULL,
                'email' => 'Anis@test.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$S4C/7LipCyDhLdBQXyi3p.ScWPNoNKIolWFkqBYaV9M819.LGCsyu',
                'remember_token' => 'Fgm5WRDzFAb77ogCHBdVp2rDriP12fEggi0x6afoMl2Q0St5Llc9mC66rIq5',
                'current_team_id' => NULL,
                'profile_photo_path' => 'profile-photos/Cp3yUEtXQMFLNkXwzobJQT0wfc2lwAbZnVZZXES5.jpg',
                'created_at' => '2021-03-31 07:43:49',
                'updated_at' => '2021-06-01 08:38:56',
                'last_seen' => '2021-06-01 08:38:56',
            ),
            2 => 
            array (
                'id' => 3,
                'role' => 'E-health Care',
                'specialty' => 'Nurse',
                'name' => 'ahmed',
                'gender' => 'm',
                'marital_status' => 'single',
                'date_of_birth' => '2017-03-02',
                'tel' => '22222222',
                'Governorate' => 'Sousse',
                'adresse' => 'Tunis, تونس, Tunisia',
                'bio' => NULL,
                'email' => 'Ahmed@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$5PlMleN8Yfel1wuwWRqp1u1KcKRaMq99qqROE8.c4BEV6lChLmByi',
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'created_at' => '2021-04-03 22:35:26',
                'updated_at' => '2021-04-04 04:44:26',
                'last_seen' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'role' => 'Patient',
                'specialty' => NULL,
                'name' => 'amina',
                'gender' => 'f',
                'marital_status' => 'single',
                'date_of_birth' => '1996-05-07',
                'tel' => '23451244',
                'Governorate' => 'Monastir',
                'adresse' => 'rue 10808, Tunis, تونس, Tunisia',
                'bio' => NULL,
                'email' => 'amina@test.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$vN/vJjnA6k/.kMY1cmE8R.2TWpSB..fNFObxpb0QGVccWACjREvFm',
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'created_at' => '2021-04-03 23:23:33',
                'updated_at' => '2021-05-30 22:01:07',
                'last_seen' => '2021-05-30 22:01:07',
            ),
            4 => 
            array (
                'id' => 5,
                'role' => 'E-health Care',
                'specialty' => 'Physiotherapist',
                'name' => 'amin',
                'gender' => 'm',
                'marital_status' => 'single',
                'date_of_birth' => '1995-01-01',
                'tel' => '23456788',
                'Governorate' => 'Nabeul',
                'adresse' => 'Borj Cédria, Tunisia, بن عروس, Tunisia',
                'bio' => 'Nurse from Tunisia!',
                'email' => 'amin@test.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$p4MrnVrLDCFP2J4dQuQ0f.I3V0.dHbOLsgNEliHTpDTA2ItZGemfW',
                'remember_token' => 'qJaZZCBSeTd3udIAKLvsrZrDEbHMM0PTcB4qz2wlvqKn3Zi6ZZMwdS4rxzRM',
                'current_team_id' => NULL,
                'profile_photo_path' => 'profile-photos/gNojfdXc3THoP0ix7ghVQ9RaiuxQxush8wKkRA32.jpg',
                'created_at' => '2021-04-05 04:28:55',
                'updated_at' => '2021-04-07 07:52:18',
                'last_seen' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'role' => 'E-health Care',
                'specialty' => 'Nurse',
                'name' => 'Nour',
                'gender' => 'f',
                'marital_status' => 'single',
                'date_of_birth' => '1990-02-01',
                'tel' => '12222222',
                'Governorate' => 'Sfax',
                'adresse' => 'Monastir, المنستير, Tunisia',
                'bio' => 'NOYR4S PRRR',
                'email' => 'nour@test.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$u4jSIMfbmj8dwjdM.MEjSeGhGxQBmusS2u7jSGqLhFQVfpkg1Pb26',
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'created_at' => '2021-04-05 04:55:34',
                'updated_at' => '2021-04-05 05:12:27',
                'last_seen' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'role' => 'E-health Care',
                'specialty' => 'Nurse',
                'name' => 'mohamed',
                'gender' => 'm',
                'marital_status' => 'single',
                'date_of_birth' => '1993-02-02',
                'tel' => '34567728',
                'Governorate' => 'Jendouba',
                'adresse' => 'Tabursuq, Bājah, Tunisia',
                'bio' => 'JVDLJVVLJV JLHGDLJHG LDJHGDJH GLDJHOJH',
                'email' => 'mohamed@test.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$CIWOsqhrJqBzJ7Q4voxyPe7YF4BrOUe8yDgQDtDmE1BcEv/JugMga',
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'created_at' => '2021-04-05 05:16:54',
                'updated_at' => '2021-04-05 05:39:37',
                'last_seen' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'role' => 'E-health Care',
                'specialty' => 'Nurse',
                'name' => 'mohamed',
                'gender' => 'm',
                'marital_status' => 'single',
                'date_of_birth' => '1993-02-02',
                'tel' => '34567728',
                'Governorate' => 'Mahdia',
                'adresse' => 'Tabursuq, Bājah, Tunisia',
                'bio' => 'JVDLJVVLJV JLHGDLJHG LDJHGDJH GLDJHOJH',
                'email' => 'moh.ahmed@test.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$CIWOsqhrJqBzJ7Q4voxyPe7YF4BrOUe8yDgQDtDmE1BcEv/JugMga',
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'created_at' => '2021-04-05 05:16:54',
                'updated_at' => '2021-04-05 05:39:37',
                'last_seen' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'role' => 'E-health Care',
                'specialty' => 'Physiotherapist',
                'name' => 'moufid',
                'gender' => 'm',
                'marital_status' => 'single',
                'date_of_birth' => '1993-02-02',
                'tel' => '34567728',
                'Governorate' => 'Tatouine',
                'adresse' => 'Tabursuq, Bājah, Tunisia',
                'bio' => 'JVDLJVVLJV JLHGDLJHG LDJHGDJH GLDJHOJH',
                'email' => 'meddebMoufid@test.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$CIWOsqhrJqBzJ7Q4voxyPe7YF4BrOUe8yDgQDtDmE1BcEv/JugMga',
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'created_at' => '2021-04-05 05:16:54',
                'updated_at' => '2021-04-05 05:39:37',
                'last_seen' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'role' => 'E-health Care',
                'specialty' => 'Physiotherapist',
                'name' => 'moufida',
                'gender' => 'f',
                'marital_status' => 'single',
                'date_of_birth' => '1993-02-02',
                'tel' => '34567728',
                'Governorate' => 'Sidi bouzid',
                'adresse' => 'Tabursuq, Bājah, Tunisia',
                'bio' => 'JVDLJVVLJV JLHGDLJHG LDJHGDJH GLDJHOJH',
                'email' => 'moufida@test.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$CIWOsqhrJqBzJ7Q4voxyPe7YF4BrOUe8yDgQDtDmE1BcEv/JugMga',
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'created_at' => '2021-04-05 05:16:54',
                'updated_at' => '2021-04-05 05:39:37',
                'last_seen' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'role' => 'E-health Care',
                'specialty' => 'Nurse',
                'name' => 'moemen',
                'gender' => 'm',
                'marital_status' => 'single',
                'date_of_birth' => '1993-02-02',
                'tel' => '34567728',
                'Governorate' => 'Kef',
                'adresse' => 'Tabursuq, Bājah, Tunisia',
                'bio' => 'JVDLJVVLJV JLHGDLJHG LDJHGDJH GLDJHOJH',
                'email' => 'moemen@test.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$CIWOsqhrJqBzJ7Q4voxyPe7YF4BrOUe8yDgQDtDmE1BcEv/JugMga',
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'created_at' => '2021-04-05 05:16:54',
                'updated_at' => '2021-04-05 05:39:37',
                'last_seen' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'role' => 'E-health Care',
                'specialty' => 'Physiotherapist',
                'name' => 'Marwen',
                'gender' => 'm',
                'marital_status' => 'single',
                'date_of_birth' => '1993-02-02',
                'tel' => '34567728',
                'Governorate' => 'Bizerte',
                'adresse' => 'Tabursuq, Bājah, Tunisia',
                'bio' => 'JVDLJVVLJV JLHGDLJHG LDJHGDJH GLDJHOJH',
                'email' => 'marwen@test.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$CIWOsqhrJqBzJ7Q4voxyPe7YF4BrOUe8yDgQDtDmE1BcEv/JugMga',
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'created_at' => '2021-04-05 05:16:54',
                'updated_at' => '2021-04-05 05:39:37',
                'last_seen' => NULL,
            ),
        ));
        
        
    }
}