<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'role' => 'admin',
                'specialty' => NULL,
                'name' => 'Admin',
                'gender' => 'm',
                'marital_status' => 'single',
                'date_of_birth' => NULL,
                'tel' => '21222222',
                'isVerified' => 1,
                'account_Verified' => 1,
                'Governorate' => 'Jendouba',
                'adresse' => '17 rue farhat hached, جندوبة, Tunisie',
                'bio' => NULL,
                'email' => 'admin@admin.com',
                'email_verified_at' => '2021-05-30 20:54:54',
                'password' => '$2y$10$idmPr5ADvyGmiEKHW.Xnu.LMZsMLUK0KAkoSpvEyp8DYJlkAsmk2e',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => 'WTWHpsX42S405AnvqAqj78S9brGz3rBOdfVPpe2JaJNLeYKKd1PSLdkvLNiB',
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'created_at' => '2021-03-21 07:16:51',
                'updated_at' => '2022-04-23 00:16:13',
                'last_seen' => '2022-04-23 00:16:13',
            ),
            1 => 
            array (
                'id' => 2,
                'role' => 'Health specialist',
                'specialty' => 'Nurse',
                'name' => 'anis',
                'gender' => 'm',
                'marital_status' => 'single',
                'date_of_birth' => '1996-05-09',
                'tel' => '25219853',
                'isVerified' => 1,
                'account_Verified' => 0,
                'Governorate' => 'Tunis',
                'adresse' => 'Rue el mar, Tunis, تونس, Tunisie',
                'bio' => NULL,
                'email' => 'Anis@test.com',
                'email_verified_at' => '2021-05-30 20:54:54',
                'password' => '$2y$10$S4C/7LipCyDhLdBQXyi3p.ScWPNoNKIolWFkqBYaV9M819.LGCsyu',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'created_at' => '2021-03-31 07:43:49',
                'updated_at' => '2021-09-24 20:17:33',
                'last_seen' => '2021-09-24 20:17:33',
            ),
            2 => 
            array (
                'id' => 3,
                'role' => 'Health specialist',
                'specialty' => 'Nurse',
                'name' => 'ahmed',
                'gender' => 'm',
                'marital_status' => 'single',
                'date_of_birth' => '2017-03-02',
                'tel' => '22222222',
                'isVerified' => 1,
                'account_Verified' => 0,
                'Governorate' => 'Sousse',
                'adresse' => 'Tunis, تونس, Tunisia',
                'bio' => NULL,
                'email' => 'Ahmed@gmail.com',
                'email_verified_at' => '2021-05-30 20:54:54',
                'password' => '$2y$10$5PlMleN8Yfel1wuwWRqp1u1KcKRaMq99qqROE8.c4BEV6lChLmByi',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'created_at' => '2021-04-03 22:35:26',
                'updated_at' => '2021-04-04 04:44:26',
                'last_seen' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'role' => 'Patient',
                'specialty' => NULL,
                'name' => 'amina',
                'gender' => 'f',
                'marital_status' => 'single',
                'date_of_birth' => '1996-05-07',
                'tel' => '23451244',
                'isVerified' => 1,
                'account_Verified' => 0,
                'Governorate' => 'Monastir',
                'adresse' => 'rue 10808, Tunis, تونس, Tunisia',
                'bio' => NULL,
                'email' => 'amina@test.com',
                'email_verified_at' => '2021-05-30 20:54:54',
                'password' => '$2y$10$vN/vJjnA6k/.kMY1cmE8R.2TWpSB..fNFObxpb0QGVccWACjREvFm',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'created_at' => '2021-04-03 23:23:33',
                'updated_at' => '2021-07-14 01:44:03',
                'last_seen' => '2021-07-14 01:44:03',
            ),
            4 => 
            array (
                'id' => 6,
                'role' => 'Health specialist',
                'specialty' => 'Nurse',
                'name' => 'Nour',
                'gender' => 'f',
                'marital_status' => 'single',
                'date_of_birth' => '1990-02-01',
                'tel' => '12222222',
                'isVerified' => 1,
                'account_Verified' => 0,
                'Governorate' => 'Sfax',
                'adresse' => 'Monastir, المنستير, Tunisia',
                'bio' => 'NOYR4S PRRR',
                'email' => 'nour@test.com',
                'email_verified_at' => '2021-05-30 20:54:54',
                'password' => '$2y$10$u4jSIMfbmj8dwjdM.MEjSeGhGxQBmusS2u7jSGqLhFQVfpkg1Pb26',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'created_at' => '2021-04-05 04:55:34',
                'updated_at' => '2021-04-05 05:12:27',
                'last_seen' => NULL,
            ),
            5 => 
            array (
                'id' => 7,
                'role' => 'Health specialist',
                'specialty' => 'Nurse',
                'name' => 'mohamed',
                'gender' => 'm',
                'marital_status' => 'single',
                'date_of_birth' => '1993-02-02',
                'tel' => '34567728',
                'isVerified' => 1,
                'account_Verified' => 0,
                'Governorate' => 'Jendouba',
                'adresse' => 'Tabursuq, Bājah, Tunisia',
                'bio' => 'JVDLJVVLJV JLHGDLJHG LDJHGDJH GLDJHOJH',
                'email' => 'mohamed@test.com',
                'email_verified_at' => '2021-05-30 20:54:54',
                'password' => '$2y$10$CIWOsqhrJqBzJ7Q4voxyPe7YF4BrOUe8yDgQDtDmE1BcEv/JugMga',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'created_at' => '2021-04-05 05:16:54',
                'updated_at' => '2021-10-23 20:50:25',
                'last_seen' => '2021-10-23 20:50:25',
            ),
            6 => 
            array (
                'id' => 8,
                'role' => 'Health specialist',
                'specialty' => 'Nurse',
                'name' => 'mohamed',
                'gender' => 'm',
                'marital_status' => 'single',
                'date_of_birth' => '1993-02-02',
                'tel' => '34567728',
                'isVerified' => 1,
                'account_Verified' => 0,
                'Governorate' => 'Mahdia',
                'adresse' => 'Tabursuq, Bājah, Tunisia',
                'bio' => 'JVDLJVVLJV JLHGDLJHG LDJHGDJH GLDJHOJH',
                'email' => 'moh.ahmed@test.com',
                'email_verified_at' => '2021-05-30 20:54:54',
                'password' => '$2y$10$CIWOsqhrJqBzJ7Q4voxyPe7YF4BrOUe8yDgQDtDmE1BcEv/JugMga',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'created_at' => '2021-04-05 05:16:54',
                'updated_at' => '2021-04-05 05:39:37',
                'last_seen' => NULL,
            ),
            7 => 
            array (
                'id' => 9,
                'role' => 'Health specialist',
                'specialty' => 'Physiotherapist',
                'name' => 'moufid',
                'gender' => 'm',
                'marital_status' => 'single',
                'date_of_birth' => '1993-02-02',
                'tel' => '34567728',
                'isVerified' => 1,
                'account_Verified' => 0,
                'Governorate' => 'Tatouine',
                'adresse' => 'Tabursuq, Bājah, Tunisia',
                'bio' => 'JVDLJVVLJV JLHGDLJHG LDJHGDJH GLDJHOJH',
                'email' => 'meddebMoufid@test.com',
                'email_verified_at' => '2021-05-30 20:54:54',
                'password' => '$2y$10$CIWOsqhrJqBzJ7Q4voxyPe7YF4BrOUe8yDgQDtDmE1BcEv/JugMga',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'created_at' => '2021-04-05 05:16:54',
                'updated_at' => '2021-04-05 05:39:37',
                'last_seen' => NULL,
            ),
            8 => 
            array (
                'id' => 10,
                'role' => 'Health specialist',
                'specialty' => 'Physiotherapist',
                'name' => 'moufida',
                'gender' => 'f',
                'marital_status' => 'single',
                'date_of_birth' => '1993-02-02',
                'tel' => '34567728',
                'isVerified' => 1,
                'account_Verified' => 0,
                'Governorate' => 'Sidi bouzid',
                'adresse' => 'Tabursuq, Bājah, Tunisia',
                'bio' => 'JVDLJVVLJV JLHGDLJHG LDJHGDJH GLDJHOJH',
                'email' => 'moufida@test.com',
                'email_verified_at' => '2021-05-30 20:54:54',
                'password' => '$2y$10$CIWOsqhrJqBzJ7Q4voxyPe7YF4BrOUe8yDgQDtDmE1BcEv/JugMga',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'created_at' => '2021-04-05 05:16:54',
                'updated_at' => '2021-04-05 05:39:37',
                'last_seen' => NULL,
            ),
            9 => 
            array (
                'id' => 11,
                'role' => 'Health specialist',
                'specialty' => 'Nurse',
                'name' => 'moemen',
                'gender' => 'm',
                'marital_status' => 'single',
                'date_of_birth' => '1993-02-02',
                'tel' => '34567728',
                'isVerified' => 1,
                'account_Verified' => 0,
                'Governorate' => 'Kef',
                'adresse' => 'Tabursuq, Bājah, Tunisia',
                'bio' => 'JVDLJVVLJV JLHGDLJHG LDJHGDJH GLDJHOJH',
                'email' => 'moemen@test.com',
                'email_verified_at' => '2021-05-30 20:54:54',
                'password' => '$2y$10$CIWOsqhrJqBzJ7Q4voxyPe7YF4BrOUe8yDgQDtDmE1BcEv/JugMga',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'created_at' => '2021-04-05 05:16:54',
                'updated_at' => '2021-04-05 05:39:37',
                'last_seen' => NULL,
            ),
            10 => 
            array (
                'id' => 12,
                'role' => 'Health specialist',
                'specialty' => 'Physiotherapist',
                'name' => 'Marwen',
                'gender' => 'm',
                'marital_status' => 'single',
                'date_of_birth' => '1993-02-02',
                'tel' => '34567728',
                'isVerified' => 1,
                'account_Verified' => 0,
                'Governorate' => 'Bizerte',
                'adresse' => 'Tabursuq, Bājah, Tunisia',
                'bio' => 'JVDLJVVLJV JLHGDLJHG LDJHGDJH GLDJHOJH',
                'email' => 'marwen@test.com',
                'email_verified_at' => '2021-05-30 20:54:54',
                'password' => '$2y$10$CIWOsqhrJqBzJ7Q4voxyPe7YF4BrOUe8yDgQDtDmE1BcEv/JugMga',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'created_at' => '2021-04-05 05:16:54',
                'updated_at' => '2021-09-24 01:08:28',
                'last_seen' => '2021-09-24 01:08:28',
            ),
            11 => 
            array (
                'id' => 13,
                'role' => 'Patient',
                'specialty' => 'Nurse',
                'name' => 'Foulen Ben Foulen',
                'gender' => 'm',
                'marital_status' => 'single',
                'date_of_birth' => '1995-01-01',
                'tel' => '+21625219853',
                'isVerified' => 1,
                'account_Verified' => 0,
                'Governorate' => 'Jendouba',
                'adresse' => 'Jendouba',
                'bio' => NULL,
                'email' => 'Foulen@test.com',
                'email_verified_at' => '2021-10-11 18:46:04',
                'password' => '$2y$10$OZCeTJU8lMkXnW0.d2dehuti9hVw7e4is/j4pWTk1aHW7c4X70HpW',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => '7Iif2p9iUAGzFTf63hTRO8BuAcLckplQ6hOElhRMUOEOJ6P2YlaJtkgnJipJ',
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'created_at' => '2021-10-11 18:39:16',
                'updated_at' => '2021-10-11 20:03:08',
                'last_seen' => '2021-10-11 19:59:55',
            ),
            12 => 
            array (
                'id' => 14,
                'role' => 'Patient',
                'specialty' => NULL,
                'name' => 'Mannix Weiss',
                'gender' => 'm',
                'marital_status' => 'married',
                'date_of_birth' => '2005-01-14',
                'tel' => NULL,
                'isVerified' => 0,
                'account_Verified' => 0,
                'Governorate' => NULL,
                'adresse' => NULL,
                'bio' => NULL,
                'email' => 'xuwovajif@mailinator.com',
                'email_verified_at' => '2021-10-15 18:27:25',
                'password' => '$2y$10$gMI8n1g2hOnmTZVTmW89AOt0JkPJeXC0hrgRMtUV9JJ7auf7N5MrG',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'created_at' => '2021-10-15 18:26:43',
                'updated_at' => '2021-10-15 18:27:27',
                'last_seen' => '2021-10-15 18:27:27',
            ),
        ));
        
        
    }
}